// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Basic.proto

package com.fuxin.common.proto;

public final class BasicProto {
  private BasicProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.fuxin.common.proto.ResStatus}
   */
  public enum ResStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>STATUS_NONE = 0;</code>
     */
    STATUS_NONE(0),
    /**
     * <code>STATUS_SUCCESS = 1;</code>
     */
    STATUS_SUCCESS(1),
    /**
     * <code>STATUS_ERROR = 2;</code>
     */
    STATUS_ERROR(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>STATUS_NONE = 0;</code>
     */
    public static final int STATUS_NONE_VALUE = 0;
    /**
     * <code>STATUS_SUCCESS = 1;</code>
     */
    public static final int STATUS_SUCCESS_VALUE = 1;
    /**
     * <code>STATUS_ERROR = 2;</code>
     */
    public static final int STATUS_ERROR_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResStatus valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ResStatus forNumber(int value) {
      switch (value) {
        case 0: return STATUS_NONE;
        case 1: return STATUS_SUCCESS;
        case 2: return STATUS_ERROR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ResStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ResStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ResStatus>() {
            public ResStatus findValueByNumber(int number) {
              return ResStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.fuxin.common.proto.BasicProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final ResStatus[] VALUES = values();

    public static ResStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ResStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.fuxin.common.proto.ResStatus)
  }

  /**
   * Protobuf enum {@code com.fuxin.common.proto.DataOrderType}
   */
  public enum DataOrderType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ORDER_NONE = 0;</code>
     */
    ORDER_NONE(0),
    /**
     * <code>ORDER_LOGIN = 1;</code>
     */
    ORDER_LOGIN(1),
    /**
     * <code>ORDER_TRANSFORM = 2;</code>
     */
    ORDER_TRANSFORM(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ORDER_NONE = 0;</code>
     */
    public static final int ORDER_NONE_VALUE = 0;
    /**
     * <code>ORDER_LOGIN = 1;</code>
     */
    public static final int ORDER_LOGIN_VALUE = 1;
    /**
     * <code>ORDER_TRANSFORM = 2;</code>
     */
    public static final int ORDER_TRANSFORM_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DataOrderType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static DataOrderType forNumber(int value) {
      switch (value) {
        case 0: return ORDER_NONE;
        case 1: return ORDER_LOGIN;
        case 2: return ORDER_TRANSFORM;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DataOrderType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DataOrderType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DataOrderType>() {
            public DataOrderType findValueByNumber(int number) {
              return DataOrderType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.fuxin.common.proto.BasicProto.getDescriptor().getEnumTypes().get(1);
    }

    private static final DataOrderType[] VALUES = values();

    public static DataOrderType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private DataOrderType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.fuxin.common.proto.DataOrderType)
  }

  public interface BaseReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.fuxin.common.proto.BaseReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.fuxin.common.proto.DataOrderType order = 1;</code>
     * @return The enum numeric value on the wire for order.
     */
    int getOrderValue();
    /**
     * <code>.com.fuxin.common.proto.DataOrderType order = 1;</code>
     * @return The order.
     */
    com.fuxin.common.proto.BasicProto.DataOrderType getOrder();

    /**
     * <code>bytes body = 2;</code>
     * @return The body.
     */
    com.google.protobuf.ByteString getBody();
  }
  /**
   * Protobuf type {@code com.fuxin.common.proto.BaseReq}
   */
  public static final class BaseReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.fuxin.common.proto.BaseReq)
      BaseReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BaseReq.newBuilder() to construct.
    private BaseReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BaseReq() {
      order_ = 0;
      body_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BaseReq();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BaseReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              order_ = rawValue;
              break;
            }
            case 18: {

              body_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fuxin.common.proto.BasicProto.internal_static_com_fuxin_common_proto_BaseReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fuxin.common.proto.BasicProto.internal_static_com_fuxin_common_proto_BaseReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fuxin.common.proto.BasicProto.BaseReq.class, com.fuxin.common.proto.BasicProto.BaseReq.Builder.class);
    }

    public static final int ORDER_FIELD_NUMBER = 1;
    private int order_;
    /**
     * <code>.com.fuxin.common.proto.DataOrderType order = 1;</code>
     * @return The enum numeric value on the wire for order.
     */
    @java.lang.Override public int getOrderValue() {
      return order_;
    }
    /**
     * <code>.com.fuxin.common.proto.DataOrderType order = 1;</code>
     * @return The order.
     */
    @java.lang.Override public com.fuxin.common.proto.BasicProto.DataOrderType getOrder() {
      @SuppressWarnings("deprecation")
      com.fuxin.common.proto.BasicProto.DataOrderType result = com.fuxin.common.proto.BasicProto.DataOrderType.valueOf(order_);
      return result == null ? com.fuxin.common.proto.BasicProto.DataOrderType.UNRECOGNIZED : result;
    }

    public static final int BODY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString body_;
    /**
     * <code>bytes body = 2;</code>
     * @return The body.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getBody() {
      return body_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (order_ != com.fuxin.common.proto.BasicProto.DataOrderType.ORDER_NONE.getNumber()) {
        output.writeEnum(1, order_);
      }
      if (!body_.isEmpty()) {
        output.writeBytes(2, body_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (order_ != com.fuxin.common.proto.BasicProto.DataOrderType.ORDER_NONE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, order_);
      }
      if (!body_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, body_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fuxin.common.proto.BasicProto.BaseReq)) {
        return super.equals(obj);
      }
      com.fuxin.common.proto.BasicProto.BaseReq other = (com.fuxin.common.proto.BasicProto.BaseReq) obj;

      if (order_ != other.order_) return false;
      if (!getBody()
          .equals(other.getBody())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ORDER_FIELD_NUMBER;
      hash = (53 * hash) + order_;
      hash = (37 * hash) + BODY_FIELD_NUMBER;
      hash = (53 * hash) + getBody().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fuxin.common.proto.BasicProto.BaseReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fuxin.common.proto.BasicProto.BaseReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fuxin.common.proto.BasicProto.BaseReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fuxin.common.proto.BasicProto.BaseReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fuxin.common.proto.BasicProto.BaseReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fuxin.common.proto.BasicProto.BaseReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fuxin.common.proto.BasicProto.BaseReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fuxin.common.proto.BasicProto.BaseReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fuxin.common.proto.BasicProto.BaseReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fuxin.common.proto.BasicProto.BaseReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fuxin.common.proto.BasicProto.BaseReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fuxin.common.proto.BasicProto.BaseReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fuxin.common.proto.BasicProto.BaseReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.fuxin.common.proto.BaseReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.fuxin.common.proto.BaseReq)
        com.fuxin.common.proto.BasicProto.BaseReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fuxin.common.proto.BasicProto.internal_static_com_fuxin_common_proto_BaseReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fuxin.common.proto.BasicProto.internal_static_com_fuxin_common_proto_BaseReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fuxin.common.proto.BasicProto.BaseReq.class, com.fuxin.common.proto.BasicProto.BaseReq.Builder.class);
      }

      // Construct using com.fuxin.common.proto.BasicProto.BaseReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        order_ = 0;

        body_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fuxin.common.proto.BasicProto.internal_static_com_fuxin_common_proto_BaseReq_descriptor;
      }

      @java.lang.Override
      public com.fuxin.common.proto.BasicProto.BaseReq getDefaultInstanceForType() {
        return com.fuxin.common.proto.BasicProto.BaseReq.getDefaultInstance();
      }

      @java.lang.Override
      public com.fuxin.common.proto.BasicProto.BaseReq build() {
        com.fuxin.common.proto.BasicProto.BaseReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.fuxin.common.proto.BasicProto.BaseReq buildPartial() {
        com.fuxin.common.proto.BasicProto.BaseReq result = new com.fuxin.common.proto.BasicProto.BaseReq(this);
        result.order_ = order_;
        result.body_ = body_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fuxin.common.proto.BasicProto.BaseReq) {
          return mergeFrom((com.fuxin.common.proto.BasicProto.BaseReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fuxin.common.proto.BasicProto.BaseReq other) {
        if (other == com.fuxin.common.proto.BasicProto.BaseReq.getDefaultInstance()) return this;
        if (other.order_ != 0) {
          setOrderValue(other.getOrderValue());
        }
        if (other.getBody() != com.google.protobuf.ByteString.EMPTY) {
          setBody(other.getBody());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fuxin.common.proto.BasicProto.BaseReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fuxin.common.proto.BasicProto.BaseReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int order_ = 0;
      /**
       * <code>.com.fuxin.common.proto.DataOrderType order = 1;</code>
       * @return The enum numeric value on the wire for order.
       */
      @java.lang.Override public int getOrderValue() {
        return order_;
      }
      /**
       * <code>.com.fuxin.common.proto.DataOrderType order = 1;</code>
       * @param value The enum numeric value on the wire for order to set.
       * @return This builder for chaining.
       */
      public Builder setOrderValue(int value) {
        
        order_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.fuxin.common.proto.DataOrderType order = 1;</code>
       * @return The order.
       */
      @java.lang.Override
      public com.fuxin.common.proto.BasicProto.DataOrderType getOrder() {
        @SuppressWarnings("deprecation")
        com.fuxin.common.proto.BasicProto.DataOrderType result = com.fuxin.common.proto.BasicProto.DataOrderType.valueOf(order_);
        return result == null ? com.fuxin.common.proto.BasicProto.DataOrderType.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.fuxin.common.proto.DataOrderType order = 1;</code>
       * @param value The order to set.
       * @return This builder for chaining.
       */
      public Builder setOrder(com.fuxin.common.proto.BasicProto.DataOrderType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        order_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.fuxin.common.proto.DataOrderType order = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOrder() {
        
        order_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString body_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes body = 2;</code>
       * @return The body.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getBody() {
        return body_;
      }
      /**
       * <code>bytes body = 2;</code>
       * @param value The body to set.
       * @return This builder for chaining.
       */
      public Builder setBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes body = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBody() {
        
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.fuxin.common.proto.BaseReq)
    }

    // @@protoc_insertion_point(class_scope:com.fuxin.common.proto.BaseReq)
    private static final com.fuxin.common.proto.BasicProto.BaseReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fuxin.common.proto.BasicProto.BaseReq();
    }

    public static com.fuxin.common.proto.BasicProto.BaseReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BaseReq>
        PARSER = new com.google.protobuf.AbstractParser<BaseReq>() {
      @java.lang.Override
      public BaseReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BaseReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BaseReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BaseReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.fuxin.common.proto.BasicProto.BaseReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BaseResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.fuxin.common.proto.BaseRes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.fuxin.common.proto.ResStatus status = 1;</code>
     * @return The enum numeric value on the wire for status.
     */
    int getStatusValue();
    /**
     * <code>.com.fuxin.common.proto.ResStatus status = 1;</code>
     * @return The status.
     */
    com.fuxin.common.proto.BasicProto.ResStatus getStatus();

    /**
     * <code>string msg = 2;</code>
     * @return The msg.
     */
    java.lang.String getMsg();
    /**
     * <code>string msg = 2;</code>
     * @return The bytes for msg.
     */
    com.google.protobuf.ByteString
        getMsgBytes();
  }
  /**
   * Protobuf type {@code com.fuxin.common.proto.BaseRes}
   */
  public static final class BaseRes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.fuxin.common.proto.BaseRes)
      BaseResOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BaseRes.newBuilder() to construct.
    private BaseRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BaseRes() {
      status_ = 0;
      msg_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BaseRes();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BaseRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              status_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fuxin.common.proto.BasicProto.internal_static_com_fuxin_common_proto_BaseRes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fuxin.common.proto.BasicProto.internal_static_com_fuxin_common_proto_BaseRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fuxin.common.proto.BasicProto.BaseRes.class, com.fuxin.common.proto.BasicProto.BaseRes.Builder.class);
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>.com.fuxin.common.proto.ResStatus status = 1;</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.com.fuxin.common.proto.ResStatus status = 1;</code>
     * @return The status.
     */
    @java.lang.Override public com.fuxin.common.proto.BasicProto.ResStatus getStatus() {
      @SuppressWarnings("deprecation")
      com.fuxin.common.proto.BasicProto.ResStatus result = com.fuxin.common.proto.BasicProto.ResStatus.valueOf(status_);
      return result == null ? com.fuxin.common.proto.BasicProto.ResStatus.UNRECOGNIZED : result;
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object msg_;
    /**
     * <code>string msg = 2;</code>
     * @return The msg.
     */
    @java.lang.Override
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <code>string msg = 2;</code>
     * @return The bytes for msg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (status_ != com.fuxin.common.proto.BasicProto.ResStatus.STATUS_NONE.getNumber()) {
        output.writeEnum(1, status_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (status_ != com.fuxin.common.proto.BasicProto.ResStatus.STATUS_NONE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, status_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fuxin.common.proto.BasicProto.BaseRes)) {
        return super.equals(obj);
      }
      com.fuxin.common.proto.BasicProto.BaseRes other = (com.fuxin.common.proto.BasicProto.BaseRes) obj;

      if (status_ != other.status_) return false;
      if (!getMsg()
          .equals(other.getMsg())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fuxin.common.proto.BasicProto.BaseRes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fuxin.common.proto.BasicProto.BaseRes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fuxin.common.proto.BasicProto.BaseRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fuxin.common.proto.BasicProto.BaseRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fuxin.common.proto.BasicProto.BaseRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fuxin.common.proto.BasicProto.BaseRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fuxin.common.proto.BasicProto.BaseRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fuxin.common.proto.BasicProto.BaseRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fuxin.common.proto.BasicProto.BaseRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fuxin.common.proto.BasicProto.BaseRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fuxin.common.proto.BasicProto.BaseRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fuxin.common.proto.BasicProto.BaseRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fuxin.common.proto.BasicProto.BaseRes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.fuxin.common.proto.BaseRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.fuxin.common.proto.BaseRes)
        com.fuxin.common.proto.BasicProto.BaseResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fuxin.common.proto.BasicProto.internal_static_com_fuxin_common_proto_BaseRes_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fuxin.common.proto.BasicProto.internal_static_com_fuxin_common_proto_BaseRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fuxin.common.proto.BasicProto.BaseRes.class, com.fuxin.common.proto.BasicProto.BaseRes.Builder.class);
      }

      // Construct using com.fuxin.common.proto.BasicProto.BaseRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        status_ = 0;

        msg_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fuxin.common.proto.BasicProto.internal_static_com_fuxin_common_proto_BaseRes_descriptor;
      }

      @java.lang.Override
      public com.fuxin.common.proto.BasicProto.BaseRes getDefaultInstanceForType() {
        return com.fuxin.common.proto.BasicProto.BaseRes.getDefaultInstance();
      }

      @java.lang.Override
      public com.fuxin.common.proto.BasicProto.BaseRes build() {
        com.fuxin.common.proto.BasicProto.BaseRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.fuxin.common.proto.BasicProto.BaseRes buildPartial() {
        com.fuxin.common.proto.BasicProto.BaseRes result = new com.fuxin.common.proto.BasicProto.BaseRes(this);
        result.status_ = status_;
        result.msg_ = msg_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fuxin.common.proto.BasicProto.BaseRes) {
          return mergeFrom((com.fuxin.common.proto.BasicProto.BaseRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fuxin.common.proto.BasicProto.BaseRes other) {
        if (other == com.fuxin.common.proto.BasicProto.BaseRes.getDefaultInstance()) return this;
        if (other.status_ != 0) {
          setStatusValue(other.getStatusValue());
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fuxin.common.proto.BasicProto.BaseRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fuxin.common.proto.BasicProto.BaseRes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int status_ = 0;
      /**
       * <code>.com.fuxin.common.proto.ResStatus status = 1;</code>
       * @return The enum numeric value on the wire for status.
       */
      @java.lang.Override public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.com.fuxin.common.proto.ResStatus status = 1;</code>
       * @param value The enum numeric value on the wire for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusValue(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.fuxin.common.proto.ResStatus status = 1;</code>
       * @return The status.
       */
      @java.lang.Override
      public com.fuxin.common.proto.BasicProto.ResStatus getStatus() {
        @SuppressWarnings("deprecation")
        com.fuxin.common.proto.BasicProto.ResStatus result = com.fuxin.common.proto.BasicProto.ResStatus.valueOf(status_);
        return result == null ? com.fuxin.common.proto.BasicProto.ResStatus.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.fuxin.common.proto.ResStatus status = 1;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(com.fuxin.common.proto.BasicProto.ResStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.fuxin.common.proto.ResStatus status = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>string msg = 2;</code>
       * @return The msg.
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msg = 2;</code>
       * @return The bytes for msg.
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msg = 2;</code>
       * @param value The msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 2;</code>
       * @param value The bytes for msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.fuxin.common.proto.BaseRes)
    }

    // @@protoc_insertion_point(class_scope:com.fuxin.common.proto.BaseRes)
    private static final com.fuxin.common.proto.BasicProto.BaseRes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fuxin.common.proto.BasicProto.BaseRes();
    }

    public static com.fuxin.common.proto.BasicProto.BaseRes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BaseRes>
        PARSER = new com.google.protobuf.AbstractParser<BaseRes>() {
      @java.lang.Override
      public BaseRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BaseRes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BaseRes> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BaseRes> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.fuxin.common.proto.BasicProto.BaseRes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fuxin_common_proto_BaseReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_fuxin_common_proto_BaseReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fuxin_common_proto_BaseRes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_fuxin_common_proto_BaseRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Basic.proto\022\026com.fuxin.common.proto\"M\n" +
      "\007BaseReq\0224\n\005order\030\001 \001(\0162%.com.fuxin.comm" +
      "on.proto.DataOrderType\022\014\n\004body\030\002 \001(\014\"I\n\007" +
      "BaseRes\0221\n\006status\030\001 \001(\0162!.com.fuxin.comm" +
      "on.proto.ResStatus\022\013\n\003msg\030\002 \001(\t*B\n\tResSt" +
      "atus\022\017\n\013STATUS_NONE\020\000\022\022\n\016STATUS_SUCCESS\020" +
      "\001\022\020\n\014STATUS_ERROR\020\002*E\n\rDataOrderType\022\016\n\n" +
      "ORDER_NONE\020\000\022\017\n\013ORDER_LOGIN\020\001\022\023\n\017ORDER_T" +
      "RANSFORM\020\002B\014B\nBasicProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_fuxin_common_proto_BaseReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_fuxin_common_proto_BaseReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_fuxin_common_proto_BaseReq_descriptor,
        new java.lang.String[] { "Order", "Body", });
    internal_static_com_fuxin_common_proto_BaseRes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_fuxin_common_proto_BaseRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_fuxin_common_proto_BaseRes_descriptor,
        new java.lang.String[] { "Status", "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
