// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Lobby.proto

package com.fuxin.common.proto;

public final class LobbyProto {
  private LobbyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CreateRoomReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.fuxin.common.proto.CreateRoomReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string RoomName = 1;</code>
     * @return The roomName.
     */
    java.lang.String getRoomName();
    /**
     * <code>string RoomName = 1;</code>
     * @return The bytes for roomName.
     */
    com.google.protobuf.ByteString
        getRoomNameBytes();

    /**
     * <code>string RoomMap = 2;</code>
     * @return The roomMap.
     */
    java.lang.String getRoomMap();
    /**
     * <code>string RoomMap = 2;</code>
     * @return The bytes for roomMap.
     */
    com.google.protobuf.ByteString
        getRoomMapBytes();

    /**
     * <code>string RoomSize = 3;</code>
     * @return The roomSize.
     */
    java.lang.String getRoomSize();
    /**
     * <code>string RoomSize = 3;</code>
     * @return The bytes for roomSize.
     */
    com.google.protobuf.ByteString
        getRoomSizeBytes();
  }
  /**
   * Protobuf type {@code com.fuxin.common.proto.CreateRoomReq}
   */
  public static final class CreateRoomReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.fuxin.common.proto.CreateRoomReq)
      CreateRoomReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CreateRoomReq.newBuilder() to construct.
    private CreateRoomReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CreateRoomReq() {
      roomName_ = "";
      roomMap_ = "";
      roomSize_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CreateRoomReq();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CreateRoomReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              roomName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              roomMap_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              roomSize_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fuxin.common.proto.LobbyProto.internal_static_com_fuxin_common_proto_CreateRoomReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fuxin.common.proto.LobbyProto.internal_static_com_fuxin_common_proto_CreateRoomReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fuxin.common.proto.LobbyProto.CreateRoomReq.class, com.fuxin.common.proto.LobbyProto.CreateRoomReq.Builder.class);
    }

    public static final int ROOMNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object roomName_;
    /**
     * <code>string RoomName = 1;</code>
     * @return The roomName.
     */
    @java.lang.Override
    public java.lang.String getRoomName() {
      java.lang.Object ref = roomName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        roomName_ = s;
        return s;
      }
    }
    /**
     * <code>string RoomName = 1;</code>
     * @return The bytes for roomName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRoomNameBytes() {
      java.lang.Object ref = roomName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roomName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROOMMAP_FIELD_NUMBER = 2;
    private volatile java.lang.Object roomMap_;
    /**
     * <code>string RoomMap = 2;</code>
     * @return The roomMap.
     */
    @java.lang.Override
    public java.lang.String getRoomMap() {
      java.lang.Object ref = roomMap_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        roomMap_ = s;
        return s;
      }
    }
    /**
     * <code>string RoomMap = 2;</code>
     * @return The bytes for roomMap.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRoomMapBytes() {
      java.lang.Object ref = roomMap_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roomMap_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROOMSIZE_FIELD_NUMBER = 3;
    private volatile java.lang.Object roomSize_;
    /**
     * <code>string RoomSize = 3;</code>
     * @return The roomSize.
     */
    @java.lang.Override
    public java.lang.String getRoomSize() {
      java.lang.Object ref = roomSize_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        roomSize_ = s;
        return s;
      }
    }
    /**
     * <code>string RoomSize = 3;</code>
     * @return The bytes for roomSize.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRoomSizeBytes() {
      java.lang.Object ref = roomSize_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roomSize_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(roomName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, roomName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(roomMap_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, roomMap_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(roomSize_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, roomSize_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(roomName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, roomName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(roomMap_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, roomMap_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(roomSize_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, roomSize_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fuxin.common.proto.LobbyProto.CreateRoomReq)) {
        return super.equals(obj);
      }
      com.fuxin.common.proto.LobbyProto.CreateRoomReq other = (com.fuxin.common.proto.LobbyProto.CreateRoomReq) obj;

      if (!getRoomName()
          .equals(other.getRoomName())) return false;
      if (!getRoomMap()
          .equals(other.getRoomMap())) return false;
      if (!getRoomSize()
          .equals(other.getRoomSize())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ROOMNAME_FIELD_NUMBER;
      hash = (53 * hash) + getRoomName().hashCode();
      hash = (37 * hash) + ROOMMAP_FIELD_NUMBER;
      hash = (53 * hash) + getRoomMap().hashCode();
      hash = (37 * hash) + ROOMSIZE_FIELD_NUMBER;
      hash = (53 * hash) + getRoomSize().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fuxin.common.proto.LobbyProto.CreateRoomReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fuxin.common.proto.LobbyProto.CreateRoomReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fuxin.common.proto.LobbyProto.CreateRoomReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fuxin.common.proto.LobbyProto.CreateRoomReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fuxin.common.proto.LobbyProto.CreateRoomReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fuxin.common.proto.LobbyProto.CreateRoomReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fuxin.common.proto.LobbyProto.CreateRoomReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fuxin.common.proto.LobbyProto.CreateRoomReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fuxin.common.proto.LobbyProto.CreateRoomReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fuxin.common.proto.LobbyProto.CreateRoomReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fuxin.common.proto.LobbyProto.CreateRoomReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fuxin.common.proto.LobbyProto.CreateRoomReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fuxin.common.proto.LobbyProto.CreateRoomReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.fuxin.common.proto.CreateRoomReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.fuxin.common.proto.CreateRoomReq)
        com.fuxin.common.proto.LobbyProto.CreateRoomReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fuxin.common.proto.LobbyProto.internal_static_com_fuxin_common_proto_CreateRoomReq_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fuxin.common.proto.LobbyProto.internal_static_com_fuxin_common_proto_CreateRoomReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fuxin.common.proto.LobbyProto.CreateRoomReq.class, com.fuxin.common.proto.LobbyProto.CreateRoomReq.Builder.class);
      }

      // Construct using com.fuxin.common.proto.LobbyProto.CreateRoomReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        roomName_ = "";

        roomMap_ = "";

        roomSize_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fuxin.common.proto.LobbyProto.internal_static_com_fuxin_common_proto_CreateRoomReq_descriptor;
      }

      @java.lang.Override
      public com.fuxin.common.proto.LobbyProto.CreateRoomReq getDefaultInstanceForType() {
        return com.fuxin.common.proto.LobbyProto.CreateRoomReq.getDefaultInstance();
      }

      @java.lang.Override
      public com.fuxin.common.proto.LobbyProto.CreateRoomReq build() {
        com.fuxin.common.proto.LobbyProto.CreateRoomReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.fuxin.common.proto.LobbyProto.CreateRoomReq buildPartial() {
        com.fuxin.common.proto.LobbyProto.CreateRoomReq result = new com.fuxin.common.proto.LobbyProto.CreateRoomReq(this);
        result.roomName_ = roomName_;
        result.roomMap_ = roomMap_;
        result.roomSize_ = roomSize_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fuxin.common.proto.LobbyProto.CreateRoomReq) {
          return mergeFrom((com.fuxin.common.proto.LobbyProto.CreateRoomReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fuxin.common.proto.LobbyProto.CreateRoomReq other) {
        if (other == com.fuxin.common.proto.LobbyProto.CreateRoomReq.getDefaultInstance()) return this;
        if (!other.getRoomName().isEmpty()) {
          roomName_ = other.roomName_;
          onChanged();
        }
        if (!other.getRoomMap().isEmpty()) {
          roomMap_ = other.roomMap_;
          onChanged();
        }
        if (!other.getRoomSize().isEmpty()) {
          roomSize_ = other.roomSize_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fuxin.common.proto.LobbyProto.CreateRoomReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fuxin.common.proto.LobbyProto.CreateRoomReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object roomName_ = "";
      /**
       * <code>string RoomName = 1;</code>
       * @return The roomName.
       */
      public java.lang.String getRoomName() {
        java.lang.Object ref = roomName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          roomName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string RoomName = 1;</code>
       * @return The bytes for roomName.
       */
      public com.google.protobuf.ByteString
          getRoomNameBytes() {
        java.lang.Object ref = roomName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          roomName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string RoomName = 1;</code>
       * @param value The roomName to set.
       * @return This builder for chaining.
       */
      public Builder setRoomName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        roomName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string RoomName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRoomName() {
        
        roomName_ = getDefaultInstance().getRoomName();
        onChanged();
        return this;
      }
      /**
       * <code>string RoomName = 1;</code>
       * @param value The bytes for roomName to set.
       * @return This builder for chaining.
       */
      public Builder setRoomNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        roomName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object roomMap_ = "";
      /**
       * <code>string RoomMap = 2;</code>
       * @return The roomMap.
       */
      public java.lang.String getRoomMap() {
        java.lang.Object ref = roomMap_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          roomMap_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string RoomMap = 2;</code>
       * @return The bytes for roomMap.
       */
      public com.google.protobuf.ByteString
          getRoomMapBytes() {
        java.lang.Object ref = roomMap_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          roomMap_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string RoomMap = 2;</code>
       * @param value The roomMap to set.
       * @return This builder for chaining.
       */
      public Builder setRoomMap(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        roomMap_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string RoomMap = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRoomMap() {
        
        roomMap_ = getDefaultInstance().getRoomMap();
        onChanged();
        return this;
      }
      /**
       * <code>string RoomMap = 2;</code>
       * @param value The bytes for roomMap to set.
       * @return This builder for chaining.
       */
      public Builder setRoomMapBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        roomMap_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object roomSize_ = "";
      /**
       * <code>string RoomSize = 3;</code>
       * @return The roomSize.
       */
      public java.lang.String getRoomSize() {
        java.lang.Object ref = roomSize_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          roomSize_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string RoomSize = 3;</code>
       * @return The bytes for roomSize.
       */
      public com.google.protobuf.ByteString
          getRoomSizeBytes() {
        java.lang.Object ref = roomSize_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          roomSize_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string RoomSize = 3;</code>
       * @param value The roomSize to set.
       * @return This builder for chaining.
       */
      public Builder setRoomSize(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        roomSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string RoomSize = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearRoomSize() {
        
        roomSize_ = getDefaultInstance().getRoomSize();
        onChanged();
        return this;
      }
      /**
       * <code>string RoomSize = 3;</code>
       * @param value The bytes for roomSize to set.
       * @return This builder for chaining.
       */
      public Builder setRoomSizeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        roomSize_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.fuxin.common.proto.CreateRoomReq)
    }

    // @@protoc_insertion_point(class_scope:com.fuxin.common.proto.CreateRoomReq)
    private static final com.fuxin.common.proto.LobbyProto.CreateRoomReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fuxin.common.proto.LobbyProto.CreateRoomReq();
    }

    public static com.fuxin.common.proto.LobbyProto.CreateRoomReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CreateRoomReq>
        PARSER = new com.google.protobuf.AbstractParser<CreateRoomReq>() {
      @java.lang.Override
      public CreateRoomReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CreateRoomReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CreateRoomReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CreateRoomReq> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.fuxin.common.proto.LobbyProto.CreateRoomReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CreateRoomResOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.fuxin.common.proto.CreateRoomRes)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.fuxin.common.proto.CreateRoomRes}
   */
  public static final class CreateRoomRes extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.fuxin.common.proto.CreateRoomRes)
      CreateRoomResOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CreateRoomRes.newBuilder() to construct.
    private CreateRoomRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CreateRoomRes() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CreateRoomRes();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CreateRoomRes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fuxin.common.proto.LobbyProto.internal_static_com_fuxin_common_proto_CreateRoomRes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fuxin.common.proto.LobbyProto.internal_static_com_fuxin_common_proto_CreateRoomRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fuxin.common.proto.LobbyProto.CreateRoomRes.class, com.fuxin.common.proto.LobbyProto.CreateRoomRes.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.fuxin.common.proto.LobbyProto.CreateRoomRes)) {
        return super.equals(obj);
      }
      com.fuxin.common.proto.LobbyProto.CreateRoomRes other = (com.fuxin.common.proto.LobbyProto.CreateRoomRes) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.fuxin.common.proto.LobbyProto.CreateRoomRes parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fuxin.common.proto.LobbyProto.CreateRoomRes parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fuxin.common.proto.LobbyProto.CreateRoomRes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fuxin.common.proto.LobbyProto.CreateRoomRes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fuxin.common.proto.LobbyProto.CreateRoomRes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.fuxin.common.proto.LobbyProto.CreateRoomRes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.fuxin.common.proto.LobbyProto.CreateRoomRes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fuxin.common.proto.LobbyProto.CreateRoomRes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fuxin.common.proto.LobbyProto.CreateRoomRes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.fuxin.common.proto.LobbyProto.CreateRoomRes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.fuxin.common.proto.LobbyProto.CreateRoomRes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.fuxin.common.proto.LobbyProto.CreateRoomRes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fuxin.common.proto.LobbyProto.CreateRoomRes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.fuxin.common.proto.CreateRoomRes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.fuxin.common.proto.CreateRoomRes)
        com.fuxin.common.proto.LobbyProto.CreateRoomResOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.fuxin.common.proto.LobbyProto.internal_static_com_fuxin_common_proto_CreateRoomRes_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.fuxin.common.proto.LobbyProto.internal_static_com_fuxin_common_proto_CreateRoomRes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.fuxin.common.proto.LobbyProto.CreateRoomRes.class, com.fuxin.common.proto.LobbyProto.CreateRoomRes.Builder.class);
      }

      // Construct using com.fuxin.common.proto.LobbyProto.CreateRoomRes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.fuxin.common.proto.LobbyProto.internal_static_com_fuxin_common_proto_CreateRoomRes_descriptor;
      }

      @java.lang.Override
      public com.fuxin.common.proto.LobbyProto.CreateRoomRes getDefaultInstanceForType() {
        return com.fuxin.common.proto.LobbyProto.CreateRoomRes.getDefaultInstance();
      }

      @java.lang.Override
      public com.fuxin.common.proto.LobbyProto.CreateRoomRes build() {
        com.fuxin.common.proto.LobbyProto.CreateRoomRes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.fuxin.common.proto.LobbyProto.CreateRoomRes buildPartial() {
        com.fuxin.common.proto.LobbyProto.CreateRoomRes result = new com.fuxin.common.proto.LobbyProto.CreateRoomRes(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.fuxin.common.proto.LobbyProto.CreateRoomRes) {
          return mergeFrom((com.fuxin.common.proto.LobbyProto.CreateRoomRes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.fuxin.common.proto.LobbyProto.CreateRoomRes other) {
        if (other == com.fuxin.common.proto.LobbyProto.CreateRoomRes.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.fuxin.common.proto.LobbyProto.CreateRoomRes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.fuxin.common.proto.LobbyProto.CreateRoomRes) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.fuxin.common.proto.CreateRoomRes)
    }

    // @@protoc_insertion_point(class_scope:com.fuxin.common.proto.CreateRoomRes)
    private static final com.fuxin.common.proto.LobbyProto.CreateRoomRes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.fuxin.common.proto.LobbyProto.CreateRoomRes();
    }

    public static com.fuxin.common.proto.LobbyProto.CreateRoomRes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CreateRoomRes>
        PARSER = new com.google.protobuf.AbstractParser<CreateRoomRes>() {
      @java.lang.Override
      public CreateRoomRes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CreateRoomRes(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CreateRoomRes> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CreateRoomRes> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.fuxin.common.proto.LobbyProto.CreateRoomRes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fuxin_common_proto_CreateRoomReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_fuxin_common_proto_CreateRoomReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fuxin_common_proto_CreateRoomRes_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_fuxin_common_proto_CreateRoomRes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Lobby.proto\022\026com.fuxin.common.proto\"D\n" +
      "\rCreateRoomReq\022\020\n\010RoomName\030\001 \001(\t\022\017\n\007Room" +
      "Map\030\002 \001(\t\022\020\n\010RoomSize\030\003 \001(\t\"\017\n\rCreateRoo" +
      "mResB\014B\nLobbyProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_fuxin_common_proto_CreateRoomReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_fuxin_common_proto_CreateRoomReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_fuxin_common_proto_CreateRoomReq_descriptor,
        new java.lang.String[] { "RoomName", "RoomMap", "RoomSize", });
    internal_static_com_fuxin_common_proto_CreateRoomRes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_fuxin_common_proto_CreateRoomRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_fuxin_common_proto_CreateRoomRes_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
